# Akil Bhuiyan

# Numpy

## Solutions

In [1]:
import numpy as np

### Problem 1

In [2]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
distinctValArr = np.intersect1d(a,b)
print (distinctValArr)

[2 4]


### Problem 2

In [21]:
a = np.array([1, 6, 11, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15])
mArr = a.reshape(5,3)
print(mArr)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### Problem 3

In [26]:
flattenArr= a.flatten()
print (flattenArr)

[ 1  6 11  2  7 12  3  8 13  4  9 14  5 10 15]


### Problem 4

In [23]:
a = np.array([1, 6, 11, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15])
mArr = a.reshape(5,3,1)
print(mArr)

[[[ 1]
  [ 6]
  [11]]

 [[ 2]
  [ 7]
  [12]]

 [[ 3]
  [ 8]
  [13]]

 [[ 4]
  [ 9]
  [14]]

 [[ 5]
  [10]
  [15]]]


### Problem 5

In [30]:
flattenArr= mArr.flatten()
flattenArr = flattenArr.reshape(5,3)
print (flattenArr)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### Problem 6

In [ ]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
temp = []
for i in range (0,len(a)):
    if a[i] not in b:
        temp.append(a[i]) 
c= np.array(temp)
print (c)

### Problem 7

[ 7 15  1  8]
