Akil Bhuiyan

Numpy Solutions

### All Imports

In [14]:
import ssl
ssl._create_default_https_context = ssl._create_unverified_context # SSL Certificate Verify
from random import randint
import numpy as np
import pandas as pd

### Problem 1

<u>Problem 1:</u>

Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays: <br>
**a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])**  <br>
**b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])**  

<br>

Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.

<br>

In [15]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

distinctValArr = np.intersect1d(a,b) # Intersect value from set a and set b
unionValArr = np.union1d(a,b) # Intersect value from set a and set b
print ("Intersect Values of set a and b: " , distinctValArr)
print ("Union Values of set a and b: " , unionValArr)

Intersect Values of set a and b:  [2 4]
Union Values of set a and b:  [ 1  2  3  4  5  6  7  8  9 10]


### Problem 2

<u>Problem 2:</u>

Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality so that you do not need to explicitly key in every integer value.

    1   6    11
    2   7    12
    3   8    13
    4   9    14
    5   10   15

<br>

In [16]:
a = np.array([1, 6, 11, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15]) # 1D Array
oneDimArr = a # Reshaping 1D arr to 2D arr with 5 rows nd 3 col
twoDimArr = a.reshape(5,3) # Reshaping 1D arr to 2D arr with 5 rows nd 3 col

print("\n1D or given arr is: " , oneDimArr)
print("\nReshaping to 2D arr w/ 5x3 is:\n" , twoDimArr)


1D or given arr is:  [ 1  6 11  2  7 12  3  8 13  4  9 14  5 10 15]

Reshaping to 2D arr w/ 5x3 is:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [17]:
# 3D array
x=randint (0,10)
my24Arr = [randint(0,10) for i in range (0,24) ]
my24Arr = np.array (my24Arr)


threeDimArr = my24Arr.reshape(2,3,4) # Reshaping 1D arr to 3D arr with 2 blocks, 3 rows nd 4 col
print("\nrandomly generated 1D arr is:\n" , my24Arr)
print("\nReshaping to 3D arr w/ 2x3x4 is:\n" , threeDimArr)


randomly generated 1D arr is:
 [ 1  5 10  7  8  8  9  1  8  5  2  9  5  3  4  0  1  6  5  1  4  8 10  8]

Reshaping to 3D arr w/ 2x3x4 is:
 [[[ 1  5 10  7]
  [ 8  8  9  1]
  [ 8  5  2  9]]

 [[ 5  3  4  0]
  [ 1  6  5  1]
  [ 4  8 10  8]]]


### Problem 3

<u>Problem 3:</u>

The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

<br>

In [18]:
# It says transform 2D arr to 1D arr
# flattten() make 2D or 3D arr to 1D arr
p3TwoDimArr = twoDimArr # get 2D arr from problem 2
flattenTwoDimArr= p3TwoDimArr.flatten()

print ("/n2D arr from Problem2 is: \n",p3TwoDimArr)
print ("\nFlatten to 1D arr becomes: \n",flattenTwoDimArr)

/n2D arr from Problem2 is: 
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]

Flatten to 1D arr becomes: 
 [ 1  6 11  2  7 12  3  8 13  4  9 14  5 10 15]


### Problem 4

<u>Problem 4:</u>

Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

<br>

In [19]:

p4TwoDimArr = twoDimArr # get 2D array from problem 2 , (it is 5x3 2D array or 15 elements)
p4ThreeDimArr = p4TwoDimArr.reshape(1,5,3)  # 1 block 5 rows 3 col
print ("\n2D Arr from problem2 is: \n",p4TwoDimArr)
print ("\n2D Arr to 3D arr is: \n",p4ThreeDimArr)




2D Arr from problem2 is: 
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]

2D Arr to 3D arr is: 
 [[[ 1  6 11]
  [ 2  7 12]
  [ 3  8 13]
  [ 4  9 14]
  [ 5 10 15]]]


### Problem 5
<u>Problem 5:</u>

Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

<br>

In [20]:
p5ThreeDimArr = p4ThreeDimArr # get 3D arr from problem 4 (1x5x3)
p5TwoDimArr = p5ThreeDimArr.reshape(5,3) # Transfor back to 2D arr
print ("\n3D arr from problem4 is: \n",p5ThreeDimArr)
print ("\nTransform 3D arr to 2D arr is : \n",p5TwoDimArr)


3D arr from problem4 is: 
 [[[ 1  6 11]
  [ 2  7 12]
  [ 3  8 13]
  [ 4  9 14]
  [ 5 10 15]]]

Transform 3D arr to 2D arr is : 
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


### Problem 6

<u>Problem 6:</u>

You are given the following two arrays: <br>
**a = np.array([12, 5, 7, 15, 3, 1, 8])**  <br>
**b = np.array([14, 6, 3, 11, 19, 12, 5])** 

<br>

Write a Python/Numpy code block that removes from array **a** any items that are also present in array **b**.

<br>

In [21]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
temp = []
for i in range (0,len(a)):
    if a[i] not in b:
        temp.append(a[i]) 
c= np.array(temp)
print ("\nNew Arr that removes val from a that present in b \nNew arr a is: a = ",c)


New Arr that removes val from a that present in b 
New arr a is: a =  [ 7 15  1  8]


### Problem 7
<u>Problem 7:</u>

Answer the following questions about the accompanying data file.

1. What is the maximum yearly NYC consumption of water in millions of gallons per day?

2. How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.
3. What is the mean and the standard deviation of the per capita daily water consumption?
4. What is the increase or decrease in population from year to year? Use NumPy's 'diff' function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

<br>

[Module6_Data.xlsx](https://drive.google.com/open?id=1Ge48f7AP7-RC5Nx6280ktxhXD8BF0QSF)

In [22]:
csvv = 'https://raw.githubusercontent.com/iakil/CSCI381_DataScience/main/Data/Module6_Data.csv'
df = pd.read_csv (csvv) # read csv file using pandas
df.head() # Print first 5

Year  New York City Population  NYC Consumption(Million gallons per day)  \
0  1979                 7102100.0                                    1512.0   
1  1980                 7071639.0                                    1506.0   
2  1981                 7089241.0                                    1309.0   
3  1982                 7109105.0                                    1382.0   
4  1983                 7181224.0                                    1424.0   

   Per Capita(Gallons per person per day)  
0                                     213  
1                                     213  
2                                     185  
3                                     194  
4                                     198

#### Part 1

What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [23]:
# to_numpy() convert to numpy and gives numpy functionality
maxConsump=np.max(df.to_numpy()[:,2]) # max val of 3rd col
print(maxConsump)

1512.0


#### Part 2

How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

In [24]:
yearr= np.shape(df['Year'].to_numpy()) # find the shape of the col
print(f"Total year is: {yearr[0]}")

Total year is: 39


#### Part 3

What is the mean and the standard deviation of the per capita daily water consumption?

In [25]:
meann = np.mean(df['Per Capita(Gallons per person per day)'].to_numpy())
stdd = np.abs(np.std(df['Per Capita(Gallons per person per day)'].to_numpy())) # std cant be negative

print (f"Mean: {meann}\nStandard Deviation: {stdd}")

Mean: 160.30769230769232
Standard Deviation: 31.51894330370624


#### Part 4

What is the increase or decrease in population from year to year? Use NumPy's `'diff'` function to create an array of differences and save that to a variable called `"pop_diff"`, then print that variable to the screen.

In [26]:
pop_diff = np.diff(df['New York City Population'].to_numpy()) # alt [:,1] 
#pop_diff = np.diff(df.to_numpy() [:,1]) # alt [:,1]  since its 2nd col

print(pop_diff)

#Subtract 1st val from 2nd val

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
